version: '3.1'

networks:
  seedbox:
    external:
      name: seedbox

  monitoring:
    external:
      name: monitoring

services:
  seedbox-rtorrent:
    restart: always
    container_name: seedbox-rtorrent
    build: .
    ports:
      - 8080:80
    env_file: .env
    volumes:
      - ${STORAGE_PATH}/dtorrent/downloaded:/var/rtorrent/downloaded
      - ${STORAGE_PATH}/dtorrent/torrent:/var/rtorrent/torrents
      - ${STORAGE_PATH}/dtorrent/session:/var/rtorrent/session
      - ${STORAGE_PATH}/dtorrent/logs:/var/rtorrent/logs
      - ./Docker/supervisor/conf.d/dev/node.supervisor.conf:/etc/supervisor/conf.d/prod/node.supervisor.conf
      - ./webservice:/var/app
    networks:
      - seedbox

  seedbox-rtorrent_exporter:
    image: ${IMAGE_RTORRENT_EXPORTER}
    restart: always
    container_name: seedbox-rtorrent_exporter
    command: ["-rtorrent.addr", "http://seedbox-rtorrent/RPC2"]
    networks:
      - seedbox
      - monitoring