version: '3.1'

networks:
  seedbox:
    external:
      name: seedbox

services:
  rtorrent:
    build: .
    env_file: .env
    volumes:
      - ${STORAGE_PATH}/dtorrent/downloaded:/var/rtorrent/downloaded
      - ${STORAGE_PATH}/dtorrent/torrent:/var/rtorrent/torrents
      - ${STORAGE_PATH}/dtorrent/logs:/var/rtorrent/logs
      - ./webservice:/var/app
    networks:
      - seedbox